### ISSUE TITLE
Interoperate with WeaveDNS

### ISSUE THREAD

**Issue by davedoesdev** [davedoesdev/fold#4]
Weave now has its own DNS server.
Fold should interoperate with that.
Outgoing queries _should_ be okay - should be able to point to the Weave DNS server.
We need weave to be able to query fold DNS entries.
Could use the weave DNS HTTP API to push entries in.

**Comment by davedoesdev** [comment]
Similarly with automatic address allocation - is there any way of participating in that?

**Comment by rade** [comment]
Not sure what the question is, but weaveDNS does use a fallback server - whatever nameserver docker normally points containers at - for any queries outside the weaveDNS domain.

**Comment by davedoesdev** [comment]
Thanks for that, I'll give it a try. I'm assuming I can still make queries to weaveDNS for weave addresses?

How is the automatic address allocation implemented? Can I get an external process to participate in that and allocate addresses for itself on a Weave network?

**Comment by rade** [comment]
> I'm assuming I can still make queries to weaveDNS for weave addresses?

Yes, as I said, the fallback server is queried for anything *outside* the weaveDNS domain.

> Can I get an external process to participate in that and allocate addresses for itself on a Weave network?

There's a lot more to participating in the weave network than allocating an IP address.

Perhaps you are looking for the [service export](http://docs.weave.works/weave/latest_release/features.html#service-export) and [service import](http://docs.weave.works/weave/latest_release/features.html#service-import) features of weave?

**Comment by davedoesdev** [comment]
When I start a VM (KVM), I want to give it an IP address from a Weave range - i.e. ask Weave for the next automatically allocated address in its range.

**Comment by rade** [comment]
> When I start a VM (KVM), I want to give it an IP address from a Weave range

Why?

**Comment by davedoesdev** [comment]
So I don't have to my own allocation :)
At the moment I'm using mixed automatic and manual allocation which works (I can ping between my VMs and containers) but obviously I have to manage the VM address allocation myself.

**Comment by rade** [comment]
> At the moment I'm using mixed automatic and manual allocation which works (I can ping between my VMs and containers) but obviously I have to manage the VM address allocation myself.

To clarify, are these VMs hosting containers or not?

`weave expose`, which is the documented way of enabling container host<->container communication, allocates an IP address if none is supplied.

**Comment by davedoesdev** [comment]
No, these are VMs on the Weave network. Fold (this project) creates `iptables`, `ip6tables` and `ebtables` rules to do the routing and uses `nfdhcpd` to give the VMs their addresses (and act as a DNS server).

**Comment by rade** [comment]
I see. The weave script invokes an http api on the weave container for allocating and freeing addresses. You could use that.

**Comment by davedoesdev** [comment]
That would be cool - thanks for your help.

**Comment by davedoesdev** [comment]
Weave DNS server is available on Docker bridge device (`docker0` or `DOCKER_BRIDGE`).
So need to get `nfdhcpd` to (optionally) forward DNS requests to there.

**Comment by davedoesdev** [comment]
DNS interoperability (both ways) is done.
Need to see if can automatically allocate IP address from `fold`.

**Comment by davedoesdev** [comment]
@rade I'm not sure about using IPAM. I can see how you're making an HTTP call to allocate the address. Who clears up the allocation when the container exits? Thanks.

**Comment by rade** [comment]
> Who clears up the allocation when the container exits? Thanks.

Weave does.

Or you can do it manually via the HTTP API. See the code for `detach` in the script.

**Comment by davedoesdev** [comment]
What events does Weave listen for?
I'm deleting my device (which is mastered to the `weave` bridge) but the IP address allocation doesn't seem to be being released.

**Comment by rade** [comment]
> What events does Weave listen for?

Docker events indicating container death.

For anything else you must call the HTTP API.

**Comment by davedoesdev** [comment]
Ah yes, got it - I was looking at the `detach` function rather than the `case` statement.

**Comment by davedoesdev** [comment]
The `DELETE` works. Thanks for your help @rade, much appreciated.

**Comment by davedoesdev** [comment]
Closed by https://github.com/davedoesdev/fold/commit/c8e68f89b225173a781cea43488f796839efdefb
